"""渠道无关的可信 Action Runtime（只读最小纵向闭环）。"""

from xiaoban.trusted_runtime.channels import (
    PLATFORM_CLI,
    PLATFORM_FEISHU,
    PLATFORM_WEB,
    PLATFORM_WECHAT,
    envelope_from_feishu_event,
    envelope_from_wechat_event,
    evaluate_channel_answer,
    identity_from_envelope,
)
from xiaoban.trusted_runtime.completion_guard import (
    check_completion,
    check_mystand_final_answer,
    project_answer,
)
from xiaoban.trusted_runtime.turns import (
    activate_turn,
    begin_action,
    begin_turn,
    build_work_turn,
    classify_interaction,
    current_turn,
    deactivate_turn,
    finish_action,
    gate_registry_action,
)
from xiaoban.trusted_runtime.types import (
    ACTION_OUTPUT_CONTRACTS,
    ActionCall,
    ActionResult,
    CommandEnvelope,
    CompletionDecision,
    EvidenceEnvelope,
    IndexReceipt,
    PreActionDecision,
    TrustedIdentity,
    WorkTurn,
)

__all__ = [
    "ACTION_OUTPUT_CONTRACTS",
    "ActionCall",
    "ActionResult",
    "CommandEnvelope",
    "CompletionDecision",
    "EvidenceEnvelope",
    "IndexReceipt",
    "PLATFORM_CLI",
    "PLATFORM_FEISHU",
    "PLATFORM_WEB",
    "PLATFORM_WECHAT",
    "PreActionDecision",
    "TrustedIdentity",
    "WorkTurn",
    "activate_turn",
    "begin_action",
    "begin_turn",
    "build_work_turn",
    "check_completion",
    "check_mystand_final_answer",
    "classify_interaction",
    "current_turn",
    "deactivate_turn",
    "envelope_from_feishu_event",
    "envelope_from_wechat_event",
    "evaluate_channel_answer",
    "finish_action",
    "gate_registry_action",
    "identity_from_envelope",
    "project_answer",
]
